// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: eejbvayechumqlklsgnh

class SupabaseConfig {
  static const String supabaseUrl = 'https://eejbvayechumqlklsgnh.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlamJ2YXllY2h1bXFsa2xzZ25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzA5MjgsImV4cCI6MjA3MTcwNjkyOH0.leQvxXeMlBW8REzaYF0LFsRUYNmL_W1lb-GfSJ9aJvg';
}
